name: Build

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build with Gradle
        run: ./gradlew lintDebug ktlintCheck
  assemble-phone:
    name: Assemble phone
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build with Gradle
        run: ./gradlew :app:phone:assembleDebug
        # Upload all build artifacts in separate steps. This can be shortened once https://github.com/actions/upload-artifact/pull/354 is merged.
      - name: Upload artifact phone-universal-debug.apk
        uses: actions/upload-artifact@v3
        with:
          name: phone-universal-debug.apk
          path: ./app/phone/build/outputs/apk/debug/phone-universal-debug.apk
      - name: Upload artifact phone-arm64-v8a-debug.apk
        uses: actions/upload-artifact@v3
        with:
          name: phone-arm64-v8a-debug.apk
          path: ./app/phone/build/outputs/apk/debug/phone-arm64-v8a-debug.apk
      - name: Upload artifact phone-armeabi-v7a-debug.apk
        uses: actions/upload-artifact@v3
        with:
          name: phone-armeabi-v7a-debug.apk
          path: ./app/phone/build/outputs/apk/debug/phone-armeabi-v7a-debug.apk
      - name: Upload artifact phone-x86_64-debug.apk
        uses: actions/upload-artifact@v3
        with:
          name: phone-x86_64-debug.apk
          path: ./app/phone/build/outputs/apk/debug/phone-x86_64-debug.apk
      - name: Upload artifact phone-x86-debug.apk
        uses: actions/upload-artifact@v3
        with:
          name: phone-x86-debug.apk
          path: ./app/phone/build/outputs/apk/debug/phone-x86-debug.apk
  assemble-tv:
    name: Assemble TV
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build with Gradle
        run: ./gradlew :app:tv:assembleDebug
        # Upload all build artifacts in separate steps. This can be shortened once https://github.com/actions/upload-artifact/pull/354 is merged.
      - name: Upload artifact tv-universal-debug.apk
        uses: actions/upload-artifact@v3
        with:
          name: tv-universal-debug.apk
          path: ./app/tv/build/outputs/apk/debug/tv-universal-debug.apk
      - name: Upload artifact tv-arm64-v8a-debug.apk
        uses: actions/upload-artifact@v3
        with:
          name: tv-arm64-v8a-debug.apk
          path: ./app/tv/build/outputs/apk/debug/tv-arm64-v8a-debug.apk
      - name: Upload artifact tv-armeabi-v7a-debug.apk
        uses: actions/upload-artifact@v3
        with:
          name: tv-armeabi-v7a-debug.apk
          path: ./app/tv/build/outputs/apk/debug/tv-armeabi-v7a-debug.apk
      - name: Upload artifact tv-x86_64-debug.apk
        uses: actions/upload-artifact@v3
        with:
          name: tv-x86_64-debug.apk
          path: ./app/tv/build/outputs/apk/debug/tv-x86_64-debug.apk
      - name: Upload artifact tv-x86-debug.apk
        uses: actions/upload-artifact@v3
        with:
          name: tv-x86-debug.apk
          path: ./app/tv/build/outputs/apk/debug/tv-x86-debug.apk
